# Travis CI Configuration File

language: php

php:
    - 5.4
    - 5.5

env:
    - WP_VERSION=master WP_MULTISITE=0
    - WP_VERSION=3.8.0 WP_MULTISITE=0
    - WP_VERSION=3.7.1 WP_MULTISITE=0
    - WP_VERSION=3.6.1 WP_MULTISITE=0
    - WP_VERSION=master WP_MULTISITE=1
    - WP_VERSION=3.8.0 WP_MULTISITE=1
    - WP_VERSION=3.7.1 WP_MULTISITE=1
    - WP_VERSION=3.6.1 WP_MULTISITE=1

before_script:
    - composer install
    - vendor/bin/phing prepare

script: vendor/bin/phing

branches:
  only:
    - master
    - develop